# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: base-image

description: Zaoth OS Base Image.


base-image: quay.io/fedora/fedora-bootc
image-version: latest 

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  - type: dnf
    install:
      packages:
        - micro
        - git
        - podman
        - podman-compose

        # filesystem  
        - exfatprogs
        - ntfs-3g

        # audio
        - pipewire
        - pipewire-pulseaudio
        - pipewire-alsa
        - wireplumber
        - pamixer

        # gpu / vulkan
        - mesa-dri-drivers
        - mesa-vulkan-drivers
        - mesa-libGL
        - mesa-libEGL
        - vulkan-loader
        - vulkan-tools
        - virglrenderer

        # devices
        - libinput

        # wayland protocol
        - wayland
        - wayland-utils

        # network
        - bluez
        - bluez-tools
        - NetworkManager-wifi
        - NetworkManager-libnm
        - iw
        - brightnessctl

        # session
        - dbus
        - dbus-daemon
        - xdg-user-dirs
        - xdg-utils

        # Portals
        - xdg-desktop-portal
        - lxqt-policykit
  
  - type: systemd
    system:
      enabled:        
        - bluetooth.service
        - NetworkManager.service
  
  - type: initramfs
